/**
 * Bakes the deployment manifests and the recorded rounds into `src/generated/data.ts`.
 *
 * The dashboard is a static export, so there is nothing at runtime that can read a file.
 * Everything a judge needs to look at with no wallet and no credentials is compiled in here
 * instead. Recorded rounds from `backend/data/bundles/` take precedence; the fixtures in
 * `web/fixtures/` fill in when the appraisal service has not produced a round yet, and they
 * are labelled as fixtures so nothing is presented as live data that is not.
 *
 * Runs automatically before `dev` and `build`.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');
const BUNDLES = join(ROOT, 'backend', 'data', 'bundles');
const DEPLOYMENTS = join(ROOT, 'deployments');
const FIXTURES = join(HERE, '..', 'fixtures');
const DEST = join(HERE, '..', 'src', 'generated');

const readJson = (p) => JSON.parse(readFileSync(p, 'utf8'));
const jsonFiles = (dir) =>
  existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith('.json')).sort() : [];

// --- deployments -----------------------------------------------------------------------

const deployments = {};
for (const file of jsonFiles(DEPLOYMENTS)) {
  const d = readJson(join(DEPLOYMENTS, file));
  const chainId = Number(d.chainId ?? file.replace('.json', ''));
  if (!Number.isFinite(chainId)) continue;
  deployments[chainId] = { ...d, chainId };
}

// --- rounds ----------------------------------------------------------------------------

/** `<assetId>-latest.json` duplicates a timestamped file; skip it so rounds are not doubled. */
const isAlias = (name) => name.endsWith('-latest.json');

let rounds = jsonFiles(BUNDLES)
  .filter((f) => !isAlias(f))
  .map((f) => ({ ...readJson(join(BUNDLES, f)), source: 'recorded' }));

// Only `fixture-*.json` are rounds; the directory also holds the attestation snapshot and a
// documented example of the deployment manifest.
const fixtures = jsonFiles(FIXTURES)
  .filter((f) => f.startsWith('fixture-'))
  .map((f) => ({ ...readJson(join(FIXTURES, f)), source: 'fixture' }));

// Keep fixtures alongside recorded rounds when the recorded set does not yet cover both a
// published outcome and a refusal — the refusal is the thing the dashboard exists to show.
const covers = (set, published) =>
  set.some((b) => (b.onChain ? b.onChain.published === published : b.summary?.wouldHalt === !published));

if (rounds.length === 0) {
  rounds = fixtures;
} else {
  for (const f of fixtures) {
    const published = f.onChain?.published ?? false;
    if (!covers(rounds, published)) rounds.push(f);
  }
}

rounds.sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1));

const attestation = existsSync(join(FIXTURES, 'attestation.json'))
  ? readJson(join(FIXTURES, 'attestation.json'))
  : null;

// --- emit ------------------------------------------------------------------------------

mkdirSync(DEST, { recursive: true });

const banner =
  '// Generated by scripts/sync-data.mjs. Do not edit by hand.\n' +
  `// ${rounds.length} recorded round(s), ${Object.keys(deployments).length} deployment manifest(s).\n\n`;

writeFileSync(
  join(DEST, 'data.ts'),
  banner +
    `import type { AppraisalBundle } from '@/lib/bundle';\n` +
    `import type { Deployment } from '@/lib/deployments';\n` +
    `import type { AttestationSnapshot } from '@/lib/attestation';\n\n` +
    `export const DEPLOYMENTS: Record<number, Deployment> = ${JSON.stringify(deployments, null, 2)};\n\n` +
    `export const ROUNDS: AppraisalBundle[] = ${JSON.stringify(rounds, null, 2)} as unknown as AppraisalBundle[];\n\n` +
    `export const ATTESTATION_SNAPSHOT: AttestationSnapshot | null = ${JSON.stringify(attestation, null, 2)};\n`,
);

console.log(
  `synced ${rounds.length} round(s) (${rounds.filter((r) => r.source === 'recorded').length} recorded, ` +
    `${rounds.filter((r) => r.source === 'fixture').length} fixture) and ` +
    `${Object.keys(deployments).length} deployment(s)`,
);
