// Regenerates src/abi/*.ts from the Foundry build output.
//
// The ABIs are committed rather than read at runtime so the package stands alone once
// published: a consumer installing @assay/sdk has no Foundry, no out/ directory and no
// compiler. Run `pnpm abi` after any change to src/*.sol and commit the result.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(process.env.ASSAY_FORGE_OUT ?? join(HERE, '..', '..', 'out'));
const ABI_DIR = join(HERE, '..', 'src', 'abi');

/** artifact name -> exported const name */
const CONTRACTS = {
  AssayOracle: 'assayOracleAbi',
  AssetRegistry: 'assetRegistryAbi',
  AttestationRegistry: 'attestationRegistryAbi',
  AssayVault: 'assayVaultAbi',
};

const BANNER = '// Generated by scripts/gen-abi.mjs from the Foundry build output. Do not edit.\n\n';

mkdirSync(ABI_DIR, { recursive: true });

const files = [];
for (const [artifact, constName] of Object.entries(CONTRACTS)) {
  const path = join(OUT_DIR, `${artifact}.sol`, `${artifact}.json`);
  const { abi } = JSON.parse(readFileSync(path, 'utf8'));
  if (!Array.isArray(abi) || abi.length === 0) throw new Error(`empty abi in ${path}`);
  const file = `${constName.replace(/Abi$/, '')}.ts`;
  writeFileSync(
    join(ABI_DIR, file),
    `${BANNER}export const ${constName} = ${JSON.stringify(abi, null, 2)} as const;\n`,
  );
  files.push({ file, constName, entries: abi.length });
}

const index =
  BANNER +
  files.map((f) => `export {${f.constName}} from './${f.file.replace(/\.ts$/, '.ts')}';`).join('\n') +
  '\n';
writeFileSync(join(ABI_DIR, 'index.ts'), index);

for (const f of files) console.log(`${f.file.padEnd(26)} ${f.entries} entries`);
